apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-data-inntekt
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-data-inntekt-v2
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: KAFKA_PRODUKT_TOPIC
      value: teamdagpenger.{{ data.topic }}
  accessPolicy:
    outbound:
      external:
        - host: "g.nav.no"
